/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DealerRole;

import Business.Auction.Auction;
import Business.Auction.DuplicateAuctionNameException;
import Business.Member.Dealer;
import LoggerUtil.LogRecord;
import java.awt.CardLayout;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class CreateAuction extends javax.swing.JPanel {

    /**
     * Creates new form CustomerScreen
     */
    JPanel userProcessContainer;
    Dealer dealer;
    private static final String usernameRegex = "^[a-zA-Z][a-zA-Z0-9.,$;]+$";
    Pattern usernamenormalpattern = Pattern.compile(usernameRegex);
    Matcher matchUserNameNormal;
    
    public CreateAuction(JPanel upc,Dealer dealer) {
        initComponents();
        userProcessContainer = upc;
        this.dealer = dealer;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createauctButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aucName = new javax.swing.JTextField();
        backButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));

        createauctButton.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        createauctButton.setText("Create");
        createauctButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createauctButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Create Auction");

        jLabel2.setText("Auction Name");

        backButton1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backButton1.setText("<< Back");
        backButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(aucName, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(createauctButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aucName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(createauctButton)
                    .addComponent(backButton1))
                .addContainerGap(194, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createauctButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createauctButtonActionPerformed
        // TODO add your handling code here:
        
        
        Auction auction = new Auction();
        auction.setName(aucName.getText());
        
        matchUserNameNormal = usernamenormalpattern.matcher(aucName.getText());
        
        if(aucName.getText().isEmpty()){
           JOptionPane.showMessageDialog(null, "Fields cannot be empty", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else if(!(matchUserNameNormal.matches()))
      {
           JOptionPane.showMessageDialog(this, "Please Enter proper user name");
           return;
      }
        else{
            
            try {
            LogRecord.log(Level.INFO, aucName.getText()+" Auction Created");
            dealer.addAuction(auction);
        } catch (DuplicateAuctionNameException ex) {
            
            LogRecord.log(Level.SEVERE, ex.getMessage());
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }
            JOptionPane.showMessageDialog(this, "Auction Created");
        }
        aucName.setText("");
    }//GEN-LAST:event_createauctButtonActionPerformed

    private void backButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton1ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aucName;
    private javax.swing.JButton backButton1;
    private javax.swing.JButton createauctButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
