/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DealerRole;


import Business.Auction.Auction;
import Business.Product.Product;
import java.awt.CardLayout;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cassiangonsalves
 */
public class DealerViewProduct extends javax.swing.JPanel {

     JPanel userProcessContainer;
     Auction auction;
    /**
     * Creates new form ViewFlights
     */
    public DealerViewProduct(JPanel upc, Auction auction) {
      initComponents();
      userProcessContainer = upc;
      this.auction = auction;
      refreshTable();
    }
   
    private void refreshTable()
    {
        int rowCount = dealerViewProduct.getRowCount();
        DefaultTableModel model = (DefaultTableModel)dealerViewProduct.getModel();
        for(int i = rowCount-1; i>=0; i--)
        {
            model.removeRow(i);
        }
        
        for(Product product: auction.getProductsList())
        {
            Object row[] = new Object[6];
            row[0] =  product.getId();
            row[1] = product;
            row[2] = product.getMinBid();
            row[3] = product.getBiddingStatus()?"Sold":"Unsold";
            row[4] = product.getMaximumBid()==null?"NA":product.getMaximumBid();
            row[5] = product.getMaximumBid()==null?"NA":product.getMaximumBid().getCustomer().getId();
            model.addRow(row);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dealerViewProduct = new javax.swing.JTable();
        flightCompany = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 190, -1));

        dealerViewProduct.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dealerViewProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product ID", "Product Name", "Minimum Bid", "Bidding Status", "Maximum Bid", "Maximum Bid Customer ID"
            }
        ));
        jScrollPane1.setViewportView(dealerViewProduct);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 860, 180));

        flightCompany.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        flightCompany.setText("View Products");
        add(flightCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
                userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);


    }//GEN-LAST:event_backButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton4;
    private javax.swing.JTable dealerViewProduct;
    private javax.swing.JLabel flightCompany;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
