/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DealerRole;

import Business.Enterprise.Enterprise;
import Business.Member.Dealer;
import Business.Organization.DealerOrganization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Abhishek
 */
public class DealerWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerScreen
     */
    
    private JPanel userProcessContainer;
    private DealerOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private Dealer dealer;
    
    public DealerWorkAreaJPanel(JPanel userProcessContainer, UserAccount account, DealerOrganization organization, Enterprise enterprise) {
        initComponents();
              
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        this.dealer = (Dealer)account.getMember();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        createAuction = new javax.swing.JButton();
        ViewAuction = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Dealer Work Area");

        createAuction.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        createAuction.setText("Create Auctions");
        createAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAuctionActionPerformed(evt);
            }
        });

        ViewAuction.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        ViewAuction.setText("View Auction");
        ViewAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAuctionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ViewAuction, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(createAuction, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(createAuction)
                .addGap(27, 27, 27)
                .addComponent(ViewAuction)
                .addContainerGap(257, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAuctionActionPerformed
        // TODO add your handling code here:
        /*Go to work area(Next Screen) */
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        CreateAuction awa = new CreateAuction(userProcessContainer, dealer);
        userProcessContainer.add(awa);
        layout.next(userProcessContainer);
        
        
    }//GEN-LAST:event_createAuctionActionPerformed

    private void ViewAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAuctionActionPerformed
        // TODO add your handling code here:
        
                        /*Go to work area(Next Screen) */
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        ViewAuctions awa = new ViewAuctions(userProcessContainer, dealer);
        userProcessContainer.add(awa);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_ViewAuctionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ViewAuction;
    private javax.swing.JButton createAuction;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
