/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DealerRole;


import Business.Auction.Auction;
import Business.Member.Dealer;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cassiangonsalves
 */
public class ViewAuctions extends javax.swing.JPanel {

   JPanel userProcessContainer;
   Dealer dealer;
    
    /**
     * Creates new form ViewFlights
     */
    public ViewAuctions(JPanel upc, Dealer dealer) {
        initComponents();
        userProcessContainer = upc;
        this.dealer = dealer;
        refreshTable();
    }
   
    private void refreshTable()
    {
        int rowCount = dealerViewAuctions.getRowCount();
        DefaultTableModel model = (DefaultTableModel)dealerViewAuctions.getModel();
        for(int i = rowCount-1; i>=0; i--)
        {
            model.removeRow(i);
        }
        
        for(Auction auction: dealer.getAuctionList())
        {
            Object row[] = new Object[2];
            row[0] =  auction.getId();
            row[1] = auction;
            model.addRow(row);
        }
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backButton4 = new javax.swing.JButton();
        flightCompany = new javax.swing.JLabel();
        addP1 = new javax.swing.JButton();
        deleteAuction = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        dealerViewAuctions = new javax.swing.JTable();
        viewsoldproducts1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 190, -1));

        flightCompany.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        flightCompany.setText("View Auctions");
        add(flightCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 170, -1));

        addP1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        addP1.setText("Add Product");
        addP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addP1ActionPerformed(evt);
            }
        });
        add(addP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 200, -1));

        deleteAuction.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        deleteAuction.setText("Delete Auction");
        deleteAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteAuctionActionPerformed(evt);
            }
        });
        add(deleteAuction, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 200, -1));

        dealerViewAuctions.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        dealerViewAuctions.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Auction ID", "Auction Name"
            }
        ));
        jScrollPane1.setViewportView(dealerViewAuctions);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 660, 180));

        viewsoldproducts1.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        viewsoldproducts1.setText("View Auction Products");
        viewsoldproducts1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewsoldproducts1ActionPerformed(evt);
            }
        });
        add(viewsoldproducts1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deleteAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteAuctionActionPerformed
        // TODO add your handling code here:      
        int row = dealerViewAuctions.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Auction auction = (Auction)dealerViewAuctions.getValueAt(row, 1);
        this.dealer.removeAuction(auction);
        refreshTable();
    }//GEN-LAST:event_deleteAuctionActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backButton4ActionPerformed

    private void addP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addP1ActionPerformed
        int row = dealerViewAuctions.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Auction auction = (Auction)dealerViewAuctions.getValueAt(row, 1);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        AddProducts ap = new AddProducts(userProcessContainer, auction);
        userProcessContainer.add(ap);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_addP1ActionPerformed

    private void viewsoldproducts1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewsoldproducts1ActionPerformed
        int row = dealerViewAuctions.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Auction auction = (Auction)dealerViewAuctions.getValueAt(row, 1);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        DealerViewProduct vp = new DealerViewProduct(userProcessContainer, auction);
        userProcessContainer.add(vp);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewsoldproducts1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addP1;
    private javax.swing.JButton backButton4;
    private javax.swing.JTable dealerViewAuctions;
    private javax.swing.JButton deleteAuction;
    private javax.swing.JLabel flightCompany;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewsoldproducts1;
    // End of variables declaration//GEN-END:variables
}
