/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;


import Business.Auction.Auction;
import Business.Enterprise.Enterprise;
import Business.Member.Dealer;
import Business.Member.Member;
import Business.Organization.DealerOrganization;
import Business.Organization.Organization;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cassiangonsalves
 */
public class AuctionList extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private Member customer;
    
    public AuctionList(JPanel userProcessContainer, Enterprise enterprise, Member customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.customer = customer;
        refreshTable();
    }
    

    private void refreshTable()
    {
        int rowCount = auctionsListTable.getRowCount();
        DefaultTableModel model = (DefaultTableModel)auctionsListTable.getModel();
        for(int i = rowCount-1; i>=0; i--)
        {
            model.removeRow(i);
        }
        
        for(Organization org : this.enterprise.getOrganizationsList())
        {
            if(org instanceof DealerOrganization)
            {
                for(Member member: org.getMemberDirectory().getMembersList())
                {
                    Dealer dealer = (Dealer)member;
                    for(Auction auction: dealer.getAuctionList())
                    {
                        Object row[] = new Object[3];
                        row[0] =  auction.getId();
                        row[1] =  auction;
                        row[2] = dealer.getName();
                        model.addRow(row);
                    }
                }
            }
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        auctionsListTable = new javax.swing.JTable();
        flightCompany = new javax.swing.JLabel();
        backButton4 = new javax.swing.JButton();
        enterAuction = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        auctionsListTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        auctionsListTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Auction ID", "Auction Name", "Dealer Name"
            }
        ));
        jScrollPane1.setViewportView(auctionsListTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 650, 180));

        flightCompany.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        flightCompany.setText("Auction Lists");
        add(flightCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        backButton4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 190, -1));

        enterAuction.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        enterAuction.setText("Enter Auction");
        enterAuction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterAuctionActionPerformed(evt);
            }
        });
        add(enterAuction, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 220, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void enterAuctionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterAuctionActionPerformed
        int row = auctionsListTable.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Auction auction = (Auction)auctionsListTable.getValueAt(row, 1);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        ProductCatalogue pc = new ProductCatalogue(userProcessContainer, auction, customer);
        userProcessContainer.add(pc);
        layout.next(userProcessContainer);
        

    }//GEN-LAST:event_enterAuctionActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable auctionsListTable;
    private javax.swing.JButton backButton4;
    private javax.swing.JButton enterAuction;
    private javax.swing.JLabel flightCompany;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
