/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.CustomerRole;


import Business.*;
import Business.Auction.Auction;
import Business.Member.Member;
import Business.Product.Product;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cassiangonsalves
 */
public class ProductCatalogue extends javax.swing.JPanel {
     JPanel userProcessContainer;
     Auction auction;
     Member customer;
   
    
    /**
     * Creates new form ViewFlights
     */
    public ProductCatalogue(JPanel userProcessContainer, Auction auction, Member customer) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.auction = auction;
        this.customer = customer;
        refreshTable();
    }
  
    private void refreshTable()
    {
        int rowCount = customerViewProducts.getRowCount();
        DefaultTableModel model = (DefaultTableModel)customerViewProducts.getModel();
        for(int i = rowCount-1; i>=0; i--)
        {
            model.removeRow(i);
        }
        
        for(Product product: auction.getProductsList())
        {
            if(!product.getBiddingStatus())
            {
                Object row[] = new Object[3];
                row[0] =  product.getId();
                row[1] = product;
                row[2] = product.getMinBid();
                model.addRow(row);
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerViewProducts = new javax.swing.JTable();
        viewPButton = new javax.swing.JButton();
        backButton4 = new javax.swing.JButton();
        flightCompany = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        customerViewProducts.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        customerViewProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Id", "Product Name", "Minimum Bid"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(customerViewProducts);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 700, 180));

        viewPButton.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        viewPButton.setText("View Product");
        viewPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPButtonActionPerformed(evt);
            }
        });
        add(viewPButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 200, -1));

        backButton4.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backButton4.setText("<< Back");
        backButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton4ActionPerformed(evt);
            }
        });
        add(backButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 190, -1));

        flightCompany.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        flightCompany.setText("Product Catlogue");
        add(flightCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 170, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPButtonActionPerformed
        int row = customerViewProducts.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Product product = (Product)customerViewProducts.getValueAt(row, 1);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        ViewProduct p = new ViewProduct(userProcessContainer,product, customer);
        userProcessContainer.add(p);
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewPButtonActionPerformed

    private void backButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton4ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton4;
    private javax.swing.JTable customerViewProducts;
    private javax.swing.JLabel flightCompany;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton viewPButton;
    // End of variables declaration//GEN-END:variables
}
