/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryAdminRole;


import Business.DeliveryRequest.DeliveryRequest;
import Business.Member.DeliveryAdmin;
import LoggerUtil.LogRecord;
import java.awt.CardLayout;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author cassiangonsalves
 */
public class DeliveryRequests extends javax.swing.JPanel {

     JPanel userProcessContainer;
     DeliveryAdmin deliveryAdmin;
    /**
     * Creates new form ViewFlights
     */
    public DeliveryRequests(JPanel upc, DeliveryAdmin deliveryAdmin) {
      initComponents();
      userProcessContainer = upc;
      this.deliveryAdmin = deliveryAdmin;
      refreshTable();
    }
   
    private void refreshTable()
    {
        int rowCount = viewDeliveryRequest.getRowCount();
        DefaultTableModel model = (DefaultTableModel)viewDeliveryRequest.getModel();
        for(int i = rowCount-1; i>=0; i--)
        {
            model.removeRow(i);
        }
        
        for(DeliveryRequest deliveryRequest: deliveryAdmin.getDeliveryRequests())
        {
                Object row[] = new Object[6];
                row[0] =  deliveryRequest.getCustomer();
                row[1] = deliveryRequest;
                row[2] = deliveryRequest.getPhoneNumber();
                row[3] = String.valueOf(deliveryRequest.getProduct().getId());
                row[4] = deliveryRequest.getProduct();
                row[5] = deliveryRequest.isDelivered()?"Delivered":"Delivery Requested";
                model.addRow(row);
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        deliverProductButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        viewDeliveryRequest = new javax.swing.JTable();
        flightCompany = new javax.swing.JLabel();
        backButton5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        deliverProductButton.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        deliverProductButton.setText("Deliver");
        deliverProductButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliverProductButtonActionPerformed(evt);
            }
        });
        add(deliverProductButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 190, -1));

        viewDeliveryRequest.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        viewDeliveryRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Address", "Contact Number", "Product Id", "Product Name", "Delivery Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(viewDeliveryRequest);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 680, 130));

        flightCompany.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        flightCompany.setText("View Requests");
        add(flightCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 170, -1));

        backButton5.setFont(new java.awt.Font("Tahoma", 2, 13)); // NOI18N
        backButton5.setText("<< Back");
        backButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButton5ActionPerformed(evt);
            }
        });
        add(backButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 190, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void deliverProductButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliverProductButtonActionPerformed
        int row = viewDeliveryRequest.getSelectedRow();
        if(row<0) {
             JOptionPane.showMessageDialog(null, "Please select a row from the table", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }else{
                          LogRecord.log(Level.INFO, "Delivery Initiated for"+viewDeliveryRequest.getValueAt(row, 1));

        DeliveryRequest deliveryRequest = (DeliveryRequest)viewDeliveryRequest.getValueAt(row, 1);
        deliveryRequest.setDeliveryStatus(true);
        JOptionPane.showMessageDialog(null, "Product delivery initiated", "Warning", JOptionPane.WARNING_MESSAGE);
        refreshTable();
        }
    }//GEN-LAST:event_deliverProductButtonActionPerformed

    private void backButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButton5ActionPerformed
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton5;
    private javax.swing.JButton deliverProductButton;
    private javax.swing.JLabel flightCompany;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable viewDeliveryRequest;
    // End of variables declaration//GEN-END:variables
}
